---
title: "STAT 545A Homework 5"
author: "Tian Gao"
date: "2018/9/27"
output: github_document
---

# Bring rectangular data in
```{r}
## load gapminder
suppressPackageStartupMessages(library(gapminder))
## load tidyverse
suppressPackageStartupMessages(library(tidyverse))
## load forcats
suppressPackageStartupMessages(library(forcats))
## load plotly
suppressPackageStartupMessages(library(plotly))
```

# Part 1: Factor management

* Elaboration for the gapminder data set
* Drop Oceania. Filter the Gapminder data to remove observations associated with the continent of Oceania. Additionally, remove unused factor levels. Provide concrete information on the data before and after removing these rows and Oceania; address the number of rows and the levels of the affected factors.

* Reorder the levels of country or continent. Use the forcats package to change the order of the factor levels, based on a principled summary of one of the quantitative variables. Consider experimenting with a summary statistic beyond the most basic choice of the median.


# Part 2: File I/O
* Experiment with one or more of write_csv()/read_csv() (and/or TSV friends), saveRDS()/readRDS(), dput()/dget(). Create something new, probably by filtering or grouped-summarization of Singer or Gapminder. I highly recommend you fiddle with the factor levels, i.e. make them non-alphabetical (see previous section). Explore whether this survives the round trip of writing to file then reading back in.

# Part 3: Visualization design
* Remake at least one figure or create a new one, in light of something you learned in the recent class meetings about visualization design and color. Maybe juxtapose your first attempt and what you obtained after some time spent working on it. Reflect on the differences. If using Gapminder, you can use the country or continent color scheme that ships with Gapminder. Consult the dimensions listed in All the Graph Things.


* Then, make a new graph by converting this visual (or another, if you¡¯d like) to a plotly graph. What are some things that plotly makes possible, that are not possible with a regular ggplot2 graph?

# Part 4: Writing figures to file
Use ggsave() to explicitly save a plot to file. Then use  to load and embed it in your report. You can play around with various options, such as:

* Arguments of ggsave(), such as width, height, resolution or text scaling.
Various graphics devices, e.g. a vector vs. raster format.
Explicit provision of the plot object p via ggsave(..., plot = p). Show a situation in which this actually matters.
